### ISSUE TITLE
ADD YOU COMMAND DESCRIPTIONS TO THE commands.json

### ISSUE THREAD

**Issue by NobleWolf42** [NobleWolf42/Stormageddon-Bot#25]
Seriously, its the file for the help message and doubles as a easy way to double check we are not duping commands.

**Comment by CaptainZwT** [comment]
Carpenter, the amount of angry grammer in this issue is entertaining. I'll make sure to do another push tonight that cares of my commands added to the json though, just for you. Which means @CzRSpecV probably wait til the next push, since you only have one command and since the way this is, likely would result in a merge conflict.

**Comment by CaptainZwT** [comment]
My side of this is done and pushed.
